CREATE TABLE `saurabh`.`patient_info` (
  `PID` INT NOT NULL,
  `PNAME` VARCHAR(45) NULL,
  `PADDRS` VARCHAR(45) NULL,
  `AGE` INT NULL,
  `CONTACTNO` INT(10) NULL,
  `PROBLEM` VARCHAR(45) NULL,
  `DOCTOR` VARCHAR(20) NULL,
  `WARDNO` INT(5) NULL,
  PRIMARY KEY (`PID`));
